### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dglava** [nmeier/simscript#5]
There doesn't seem to be any license declared for the files. I would like to use some of it in my project (licensed under the GPLv3) and was wondering if that would be permitted?

**Comment by nmeier** [comment]
yeah, apparently there should be a license. I'm considering MIT, as it's the most permissive, does that work?

**Comment by nmeier** [comment]
added MIT license, most open and simple as per https://choosealicense.com/

**Comment by dglava** [comment]
Great, thanks!
